// ===== Core Poker Types =====
export const SHOWDOWN_SPEED_DELAYS_MS = {
    turbo: 300,
    fast: 3_000,
    normal: 6_000,
    slow: 9_000,
};
export const DEFAULT_ROOM_SETTINGS = {
    gameType: 'texas',
    maxPlayers: 6,
    spectatorAllowed: true,
    smallBlind: 50,
    bigBlind: 100,
    ante: 0,
    blindStructure: null,
    buyInMin: 2000,
    buyInMax: 20000,
    rebuyAllowed: true,
    addOnAllowed: false,
    straddleAllowed: false,
    runItTwice: false,
    runItTwiceMode: 'off',
    visibility: 'public',
    password: null,
    hostStartRequired: false,
    actionTimerSeconds: 15,
    timeBankSeconds: 60,
    timeBankRefillPerHand: 5,
    timeBankHandsToFill: 10,
    thinkExtensionSecondsPerUse: 10,
    thinkExtensionQuotaPerHour: 3,
    disconnectGracePeriod: 30,
    maxConsecutiveTimeouts: 3,
    useCentsValues: false,
    rabbitHunting: false,
    autoStartNextHand: true,
    showdownSpeed: 'normal',
    dealToAwayPlayers: false,
    revealAllAtShowdown: true,
    autoRevealOnAllInCall: true,
    autoRevealWinningHands: true,
    autoMuckLosingHands: true,
    allowShowAfterFold: false,
    allowShowCalledHandRequest: false,
    bombPotEnabled: false,
    bombPotFrequency: 0,
    doubleBoardMode: 'off',
    sevenTwoBounty: 0,
    simulatedFeeEnabled: false,
    simulatedFeePercent: 5,
    simulatedFeeCap: 0,
    allowGuestChat: true,
    autoTrimExcessBets: true,
    roomFundsTracking: false,
    botSeats: [],
    botBuyIn: undefined,
    selfPlayTurbo: false,
};
// Re-export socket events
export * from './socket-events.js';
