import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';

const DEV_SERVER_TARGET =
  process.env.VITE_DEV_SERVER_TARGET || process.env.VITE_SERVER_URL || 'http://127.0.0.1:4000';

export default defineConfig({
  plugins: [tailwindcss(), react()],
  envDir: '../../',
  server: {
    host: '127.0.0.1',
    port: 5173,
    strictPort: false,
    proxy: {
      '/socket.io': {
        target: DEV_SERVER_TARGET,
        changeOrigin: true,
        ws: true,
      },
      '/api': {
        target: DEV_SERVER_TARGET,
        changeOrigin: true,
      },
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          'vendor-react': ['react', 'react-dom', 'react-router-dom'],
          'vendor-supabase': ['@supabase/supabase-js'],
          'vendor-socket': ['socket.io-client'],
          cfr: [
            './src/pages/cfr/CfrPage.tsx',
            './src/pages/cfr/lib/cfr-constants.ts',
            './src/pages/cfr/lib/cfr-api.ts',
            './src/pages/cfr/lib/cfr-labels.ts',
            './src/pages/cfr/lib/cfr-colors.ts',
            './src/pages/cfr/lib/cfr-computations.ts',
            './src/pages/cfr/hooks/useStrategyViewer.ts',
            './src/pages/cfr/hooks/useFlopBrowser.ts',
            './src/pages/cfr/hooks/useActionTree.ts',
            './src/pages/cfr/hooks/useHandMatrix.ts',
            './src/pages/cfr/components/shared/SegmentedControl.tsx',
            './src/pages/cfr/components/shared/FilterChip.tsx',
            './src/pages/cfr/components/shared/ActionColorBar.tsx',
            './src/pages/cfr/components/shared/PokerCardDisplay.tsx',
            './src/pages/cfr/components/sidebar/FlopSidebar.tsx',
            './src/pages/cfr/components/viewer/StrategyViewer.tsx',
            './src/pages/cfr/components/viewer/HandMatrix.tsx',
            './src/pages/cfr/components/viewer/WelcomeScreen.tsx',
            './src/pages/cfr/components/training/TrainingMode.tsx',
            './src/pages/cfr/hooks/usePreflopViewer.ts',
            './src/pages/cfr/components/viewer/PreflopContent.tsx',
            './src/data/preflop-loader.ts',
            './src/components/preflop/HandGrid.tsx',
            './src/components/preflop/ScenarioSelector.tsx',
            './src/components/preflop/FrequencyDetail.tsx',
            './src/components/preflop/ActionLegend.tsx',
            './src/components/preflop/ConfigSelector.tsx',
            './src/components/preflop/DrillMode.tsx',
          ],
          solver: ['./src/pages/solver/SolverWorkspacePage.tsx'],
          club: [
            './src/pages/clubs/ClubsPage.tsx',
            './src/pages/clubs/ClubDetailView.tsx',
            './src/pages/clubs/hooks/useClubPermissions.ts',
            './src/pages/clubs/hooks/useClubTab.ts',
            './src/pages/clubs/hooks/useClubSocket.ts',
            './src/pages/clubs/hooks/useChat.ts',
            './src/pages/clubs/hooks/useNotifications.ts',
            './src/pages/clubs/hooks/useAnalytics.ts',
            './src/pages/clubs/hooks/index.ts',
            './src/pages/clubs/shared/RoleBadge.tsx',
            './src/pages/clubs/shared/StatusBadge.tsx',
            './src/pages/clubs/shared/EmptyState.tsx',
            './src/pages/clubs/shared/SkeletonRow.tsx',
            './src/pages/clubs/shared/ClubAvatar.tsx',
            './src/pages/clubs/shared/RulesSummary.tsx',
            './src/pages/clubs/shared/index.ts',
            './src/pages/clubs/modals/ConfirmActionModal.tsx',
            './src/pages/clubs/modals/GrantCreditsModal.tsx',
            './src/pages/clubs/modals/AdjustCreditsModal.tsx',
            './src/pages/clubs/modals/RenameTableModal.tsx',
            './src/pages/clubs/modals/index.ts',
            './src/pages/clubs/tabs/OverviewTab.tsx',
            './src/pages/clubs/tabs/TablesTab.tsx',
            './src/pages/clubs/tabs/CreditsTab.tsx',
            './src/pages/clubs/tabs/TransactionsTab.tsx',
            './src/pages/clubs/tabs/LeaderboardTab.tsx',
            './src/pages/clubs/tabs/RulesetsTab.tsx',
            './src/pages/clubs/tabs/InvitesTab.tsx',
            './src/pages/clubs/tabs/AuditTab.tsx',
            './src/pages/clubs/tabs/SettingsTab.tsx',
            './src/pages/clubs/tabs/ChatTab.tsx',
            './src/pages/clubs/tabs/AnalyticsTab.tsx',
            './src/pages/clubs/tabs/MembersTab.tsx',
          ],
        },
      },
    },
  },
});
