import { useRef, useEffect, useCallback, type ReactNode } from "react";

type LegalRoute = "privacy" | "terms";

const CONTACT_EMAIL = import.meta.env.VITE_CONTACT_EMAIL || "security@cardpilot.app";

function normalizePathname(pathname: string): string {
  const path = pathname.trim().toLowerCase();
  if (path.length === 0) return "/";
  return path.endsWith("/") && path !== "/" ? path.slice(0, -1) : path;
}

export function getLegalRoute(pathname: string): LegalRoute | null {
  const normalized = normalizePathname(pathname);
  if (normalized === "/privacy") return "privacy";
  if (normalized === "/terms") return "terms";
  return null;
}

export function LegalStandalonePage({ route }: { route: LegalRoute }) {
  const title = route === "privacy" ? "Privacy Policy" : "Terms of Use";
  const subtitle =
    route === "privacy"
      ? "How CardPilot stores and uses your data."
      : "Rules for using CardPilot training tables.";

  return (
    <main className="min-h-screen px-4 py-10">
      <div className="max-w-3xl mx-auto">
        <header className="mb-6 glass-card p-6">
          <a href="/" className="text-xs text-amber-400 hover:text-amber-300">
            ← Back to CardPilot
          </a>
          <h1 className="text-3xl font-bold text-white mt-3">{title}</h1>
          <p className="text-sm text-slate-400 mt-2">{subtitle}</p>
          <p className="text-xs text-slate-500 mt-2">Last updated: February 15, 2026</p>
        </header>

        <article className="glass-card p-6 space-y-5 text-sm leading-7 text-slate-200">
          {route === "privacy" ? <PrivacySection /> : <TermsSection />}
        </article>
      </div>
    </main>
  );
}

export function AppLegalFooter() {
  const footerRef = useRef<HTMLElement>(null);

  const syncHeight = useCallback(() => {
    const h = footerRef.current?.getBoundingClientRect().height ?? 0;
    document.documentElement.style.setProperty("--app-footer-h", `${h}px`);
  }, []);

  useEffect(() => {
    const el = footerRef.current;
    if (!el) return;
    syncHeight();
    const ro = new ResizeObserver(syncHeight);
    ro.observe(el);
    return () => {
      ro.disconnect();
      document.documentElement.style.setProperty("--app-footer-h", "0px");
    };
  }, [syncHeight]);

  return (
    <footer ref={footerRef} className="shrink-0 border-t border-white/5 px-4 py-2 bg-[#0a0f1a]/80 backdrop-blur-sm" style={{ paddingBottom: "max(8px, env(safe-area-inset-bottom))" }}>
      <div className="flex flex-col gap-1.5 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-[11px] text-amber-300/90">
          CardPilot uses virtual credits for training sessions.
        </p>
        <div className="flex items-center gap-3 text-[11px]">
          <a href="/privacy" className="text-slate-400 hover:text-slate-200">
            Privacy
          </a>
          <a href="/terms" className="text-slate-400 hover:text-slate-200">
            Terms
          </a>
          <a href={`mailto:${CONTACT_EMAIL}`} className="text-slate-500 hover:text-slate-300">
            {CONTACT_EMAIL}
          </a>
        </div>
      </div>
    </footer>
  );
}

function LegalSection({ heading, children }: { heading: string; children: ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-white mb-2">{heading}</h2>
      <div className="space-y-2 text-slate-300">{children}</div>
    </section>
  );
}

function PrivacySection() {
  return (
    <>
      <LegalSection heading="What we store">
        <p>We store account identifiers, room/session history, hand summaries, and hand details generated by the server.</p>
        <p>When Supabase is configured, authenticated profile fields such as display name and email may be stored by Supabase Auth.</p>
      </LegalSection>

      <LegalSection heading="Client storage">
        <p>CardPilot stores local preferences (for example display settings and panel toggles) in your browser localStorage.</p>
        <p>We do not use ad-tech cookies in the current product.</p>
      </LegalSection>

      <LegalSection heading="How data is used">
        <p>Data is used to run poker training sessions, keep hand history, and enforce room permissions.</p>
        <p>Hand history visibility is permissioned server-side and follows room/session access rules.</p>
      </LegalSection>

      <LegalSection heading="Responsible play">
        <p>CardPilot is for strategy practice only and is not a venue for real-money wagering.</p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>Privacy or data requests: <a className="text-amber-400 hover:text-amber-300" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p>
      </LegalSection>
    </>
  );
}

function TermsSection() {
  return (
    <>
      <LegalSection heading="Service scope">
        <p>CardPilot provides multiplayer poker training rooms and hand-review tools.</p>
        <p>The product is intended for educational use and does not support real-money gambling activity.</p>
      </LegalSection>

      <LegalSection heading="User conduct">
        <p>Do not exploit bugs, abuse network traffic, or attempt unauthorized access to rooms or data.</p>
        <p>Hosts may remove disruptive users and close rooms at their discretion.</p>
      </LegalSection>

      <LegalSection heading="Availability">
        <p>The service may change or be interrupted during maintenance, upgrades, or incident response.</p>
      </LegalSection>

      <LegalSection heading="No wagering relationship">
        <p>All chip balances are virtual training values with no cash value and no redemption path.</p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>Terms and safety contact: <a className="text-amber-400 hover:text-amber-300" href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a></p>
      </LegalSection>
    </>
  );
}
