param([switch]$ValidateOnly)
$ErrorActionPreference='Stop';$Repo=(Resolve-Path '.').Path
$controlId='v5_hybrid_h2_control_allinonly_same31400_20m_r1_20260713';$treatmentId='v5_hybrid_h2_treatment_showdownk200_same31400_20m_r1_20260713'
$controlDir=Join-Path $Repo "models/alpha_holdem_v5_hybrid/$controlId";$treatmentDir=Join-Path $Repo "models/alpha_holdem_v5_hybrid/$treatmentId"
$source=(Resolve-Path 'models/alpha_holdem_v5_from_zero/v5_zero_l6_exp004_pre001_exp002_multienv_exp003_boundedk_r1_20260709/v5_exp005_cutover_gate31400_checkpoint.pt').Path
$prereg=(Resolve-Path 'reports/v5_hybrid_h2_preregistration_v2_20260713.json').Path;$lock=(Resolve-Path 'reports/v5_hybrid_h2_design_lock_20260713.json').Path
if((Get-FileHash $source -Algorithm SHA256).Hash.ToLowerInvariant() -ne 'bcbb46bd01d62fcdea602269b7047323315d4e9bbcf447ea0323e289fde11a8e'){throw 'source hash'}
if((Get-FileHash $prereg -Algorithm SHA256).Hash.ToLowerInvariant() -ne 'aaf8bf30db6e757e15c1b9ae1bdd0b5e3eed379ec1dadbd23b2d8a70b1f2fa2f'){throw 'prereg hash'}
if((Get-FileHash $lock -Algorithm SHA256).Hash.ToLowerInvariant() -ne 'f4526c4175130857f34b2669a629f5a1c80410e15f32ba5975ccc7c580876c75'){throw 'design lock hash'}
$endpoint=Get-Content (Join-Path $controlDir 'h2_control_endpoint_status.json') -Raw|ConvertFrom-Json;$protocol=Get-Content (Join-Path $controlDir 'h2_control_protocol_status.json') -Raw|ConvertFrom-Json
$ready=($endpoint.overall -eq 'PASS' -and $endpoint.state -eq 'ARM_ENDPOINT_FROZEN' -and $protocol.overall -eq 'PASS' -and $protocol.first60.status -eq 'PASS_CONTROL_BASELINE_FROZEN')
$state=[pscustomobject]@{ready=$ready;endpoint=$endpoint.state;endpoint_overall=$endpoint.overall;protocol=$protocol.state;protocol_overall=$protocol.overall;treatment_dir_absent=(-not(Test-Path $treatmentDir))}
if($ValidateOnly){$state|ConvertTo-Json -Depth 5;exit $(if($ready -and -not(Test-Path $treatmentDir)){0}else{3})}
if(-not $ready){throw 'control endpoint/protocol is not exact PASS'};if(Test-Path $treatmentDir){throw 'treatment run dir already exists'}
$active=Get-CimInstance Win32_Process|Where-Object{$_.CommandLine -like '*train_v5.py*' -and $_.CommandLine -like '*v5_hybrid_h2_*'};if($active){throw 'an H2 trainer is already active'}
$mirrorLock=(Resolve-Path 'reports/h2_mirror_001_20260713/measurement_lock_v2.json').Path;$mirrorManifest=(Resolve-Path 'reports/h2_mirror_001_20260713/manifest.json').Path;$mirrorOut=Join-Path $Repo 'reports/h2_mirror_001_20260713/control_pairs.jsonl'
if(Test-Path $mirrorOut){throw 'control mirror output already exists'}
$mirrorArgs=@('-u','scripts/alpha_holdem/v5_hybrid_h2_mirror.py','run-arm','--manifest',$mirrorManifest,'--endpoint',[string]$endpoint.checkpoint_path,'--arm','control','--out',$mirrorOut,'--device','cpu','--priority','below-normal','--torch-threads','1','--torch-interop-threads','1','--measurement-lock',$mirrorLock,'--expected-lock-sha256','800c0b75e70ab5dedb54c853956d27333598f1e9ddcf6fa85162ad59e0921618')
$mirror=Start-Process python -ArgumentList $mirrorArgs -WorkingDirectory $Repo -RedirectStandardOutput (Join-Path $Repo 'reports/h2_mirror_001_20260713/control.out.log') -RedirectStandardError (Join-Path $Repo 'reports/h2_mirror_001_20260713/control.err.log') -WindowStyle Hidden -PassThru
New-Item -ItemType Directory -Path $treatmentDir|Out-Null;$prov=Join-Path $treatmentDir 'opponent_assignment_provenance.jsonl';$out=Join-Path $treatmentDir 'latest.pt'
$args=@('-u','scripts/alpha_holdem/train_v5.py','--resume',$source,'--allow-resume','--reset-optimizer','--run-id',$treatmentId,'--run-dir',$treatmentDir,'--out',$out,'--total-hands','535989661','--device','cuda','--workers','22','--hands-per-iter','16384','--rollout-mode','multi','--rollout-envs-per-worker','16','--inference-min-batch-slots','256','--inference-batch-deadline-us','1000','--ppo-epochs','4','--mini-batch-size','1024','--lr','0.0003','--gamma','0.999','--entropy-coef','0.05','--entropy-floor','0.3','--seed','20260703','--worker-seed-base','73000','--fixed-training-deal-stream','--opponent-assignment','per-iteration','--opponent-assignment-provenance-file',$prov,'--pool-strategy','loss-kbest','--k-best','5','--opponent-groups','5','--self-play-fraction','0.2','--mirror-self-play-deals','--allin-runout-ev','--allin-runout-ev-max-runouts','200','--preflop-action-prior-coef','0.01','--preflop-action-prior-target','0.24,0.36,0.38,0.02','--postflop-action-prior-coef','0.02','--postflop-action-prior-target','0.15,0.30,0.52,0.03','--critic-contract','critic_v1','--value-coef','0.5','--save-interval','1','--snapshot-every','200','--h2-window-arm','treatment','--showdown-ev-value-targets','--showdown-ev-value-target-max-runouts','200','--showdown-ev-value-target-seed','2026071401','--h2-preregistration',$prereg,'--h2-preregistration-sha256','aaf8bf30db6e757e15c1b9ae1bdd0b5e3eed379ec1dadbd23b2d8a70b1f2fa2f','--h2-design-lock',$lock,'--h2-design-lock-sha256','f4526c4175130857f34b2669a629f5a1c80410e15f32ba5975ccc7c580876c75')
$trainer=Start-Process python -ArgumentList $args -WorkingDirectory $Repo -RedirectStandardOutput (Join-Path $treatmentDir 'console.out.log') -RedirectStandardError (Join-Path $treatmentDir 'console.err.log') -WindowStyle Hidden -PassThru
$deadline=(Get-Date).AddSeconds(90);while(-not(Test-Path(Join-Path $treatmentDir 'run_manifest.json'))){if((Get-Date)-gt$deadline){Stop-Process -Id $trainer.Id -Force;throw 'treatment manifest timeout'};Start-Sleep 1}
try{powershell -NoProfile -ExecutionPolicy Bypass -File scripts/alpha_holdem/v5_rearm_watchers.ps1 -RunDir $treatmentDir;if($LASTEXITCODE-ne0){throw 'canonical rearm failed'}}catch{Stop-Process -Id $trainer.Id -Force -ErrorAction SilentlyContinue;throw}
[pscustomobject]@{status='TREATMENT_LAUNCHED_REARM_PASS';trainer_pid=$trainer.Id;mirror_control_pid=$mirror.Id;run_id=$treatmentId}|ConvertTo-Json
