#!/usr/bin/env python3
from __future__ import annotations
import argparse,hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path)->dict:return json.loads(p.read_text(encoding="utf-8-sig"))
def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--preregistration",type=Path,required=True);p.add_argument("--out",type=Path,required=True);a=p.parse_args();d=load(a.preregistration);c={}
 def ck(n,x):c.__setitem__(n,bool(x))
 ck("identity",d.get("experiment_id")=="H16" and d.get("status")=="REGISTERED_NO_LAUNCH")
 rr=d.get("route_review",{});r=ROOT/rr.get("result_path","");ra=ROOT/rr.get("audit_path","");ck("route_hashes",sha(r)==rr.get("result_sha256") and sha(ra)==rr.get("audit_sha256"));ck("route_selection",rr.get("selected_next")=="H16_REPRESENTATIVE_FULL_PPO_PERF_CAL_SAME_SCIENCE" and rr.get("route_exhausted") is False)
 s=d.get("source",{});sp=Path(s.get("checkpoint_path",""));ck("source",s.get("iteration")==35051 and s.get("hands")==576021901 and s.get("checkpoint_sha256")=="96a007039b0baa29f0c39b0bd7adc67d8ca0733a41a261203f52430e60b5ca13" and sp.is_file() and sha(sp)==s.get("checkpoint_sha256") and s.get("optimizer_preserved") is True)
 arms=d.get("arms",{});ck("arms",arms.get("order")==["control","treatment"] and arms.get("actual_hands_each")==20000000 and arms.get("minimum_endpoint_hands")==596021901 and arms.get("maximum_overshoot_hands")==50000 and arms.get("fresh_same_start") is True and arms.get("adaptive_extension") is False and arms.get("terminal_partial_reuse") is False);ck("fresh_ids","h16_control" in arms.get("control_run_id","") and "h16_treatment" in arms.get("treatment_run_id",""))
 sv=d.get("single_variable",{});ck("single_variable",sv.get("name")=="catchup_value_loss" and sv.get("control")=="MSE" and sv.get("treatment")=="SmoothL1" and sv.get("treatment_beta_raw_bb")==1.0 and sv.get("standard_ppo_critic_loss_both_arms")=="MSE" and sv.get("value_head_catchup_after_kl_stop") is True)
 pc=d.get("representative_prearm_calibration",{});ck("representative_work","FULL_TRINAL_CLIP_PPO_UPDATE" in pc.get("work","") and "THREE_VALUE_HEAD_CATCHUP_EPOCHS" in pc.get("work",""));ck("cal_shape",pc.get("rows")==4096 and pc.get("mini_batch_size")==1024 and pc.get("ppo_epochs")==4 and pc.get("target_kl")==1e-12 and pc.get("warmup_updates")==2 and pc.get("timed_updates")==8 and pc.get("repeats")==5);ck("cal_gates",pc.get("full_update_throughput_ratio_min")==0.85 and pc.get("mse_repeat_stability_ratio_min")==0.95 and pc.get("numerical_gradient_actor_scope_identity")=="MUST_PASS");ck("cal_fail_closed","FAIL_CLOSED_NO_ARM_LAUNCH" in pc.get("failure_action","") and "PCV005" in pc.get("failure_action",""));ck("cal_before_arm",pc.get("required_immediately_before_each_arm") is True and pc.get("device")=="cuda")
 cfg=d.get("frozen_common_config",{});ck("common_config",cfg.get("workers")==22 and cfg.get("target_kl")==0.03 and cfg.get("optimizer_reset") is False and cfg.get("preflop_action_prior_coef")==0.01 and cfg.get("postflop_action_prior_coef")==0.02)
 g=d.get("gates",{});ck("science_gates",g.get("endpoint_mse_primary_reduction_point_min")==0.075 and g.get("endpoint_mse_primary_ci95_lower_min")==0.0 and g.get("source_anchor_degradation_point_max")==0.05 and g.get("source_anchor_degradation_ci95_upper_max")==0.1 and g.get("mirror_pairs")==40000);ck("throughput_gates",g.get("first60_hps_ratio_min")==0.85 and g.get("full_hps_ratio_min")==0.85);ck("mirror_gates",g.get("mirror_treatment_control_ci95_lower_min_bb100")==-20.0 and g.get("mirror_treatment_source_ci95_lower_min_bb100")==-20.0)
 ck("forbidden_h15",any("H15" in x for x in d.get("forbidden_sources",[])));ri=d.get("resource_isolation",{});ck("isolation",ri.get("evaluation_during_arm")=="FORBIDDEN" and ri.get("slumbot_during_arm")=="FORBIDDEN" and "INCLUDING_FILE_READ_HASH_PROCESS_LIST" in ri.get("parent_or_delegated_observer_commands",""));ck("path1","EXISTING_EXACT_LOCKED_SIX_BELOWNORMAL" in ri.get("path1_existing_job",""));ck("no_official",d.get("external_policy",{}).get("during_arms_official_hands")==0 and d.get("authority",{}).get("official_hands")==0);ck("launch_blocked",d.get("authority",{}).get("launch","").startswith("BLOCKED_UNTIL_"));ck("route_after_terminal",d.get("judgment",{}).get("route_review_after_fail_or_inconclusive") is True)
 failed=sorted(k for k,v in c.items() if not v);rout={"schema_version":"v5.hybrid.h16.preregistration_audit.v1","checked_at":datetime.now(timezone.utc).isoformat(),"overall":"PASS" if not failed else "FAIL_CLOSED","checks":c,"checks_passed":sum(c.values()),"checks_total":len(c),"failed":failed,"preregistration_sha256":sha(a.preregistration),"behavior_launch_authority":"NONE_PREREGISTRATION_ONLY","official_hands":0};a.out.write_text(json.dumps(rout,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(json.dumps(rout,indent=2,sort_keys=True));return 0 if not failed else 2
if __name__=="__main__":raise SystemExit(main())
