#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R=ROOT/"reports/v5_h14_lock_test_pointer_correction_20260717.json";OUT=ROOT/"reports/v5_h14_lock_test_pointer_correction_audit_20260717.json"
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def main()->int:
 d=json.loads(R.read_text(encoding="utf-8"));c={};c["schema"]=d.get("schema_version")=="v5.hybrid.h14.lock_test_pointer_correction.v1";c["overall"]=d.get("overall")=="PASS_TEST_ONLY_CORRECTION_REQUIRES_SUPERSEDING_LOCK";c["v3_lock"]=sha(ROOT/"reports/v5_hybrid_h14_design_lock_v3_20260717.json")==d["superseded_lock_v3_sha256"];c["v3_audit"]=sha(ROOT/"reports/v5_hybrid_h14_design_lock_audit_v3_20260717.json")==d["superseded_lock_v3_audit_sha256"];lock=json.loads((ROOT/"reports/v5_hybrid_h14_design_lock_v3_20260717.json").read_text(encoding="utf-8"));c["old_binding"]=lock.get("tools",{}).get("scripts/alpha_holdem/test_v5_hybrid_h14_judge_contract.py")==d["old_test_sha256"];test=ROOT/"scripts/alpha_holdem/test_v5_hybrid_h14_judge_contract.py";c["new_hash"]=sha(test)==d["new_test_sha256"];src=test.read_text(encoding="utf-8");c["latest_versioned_pointer"]='glob("v5_hybrid_h14_design_lock_v*_20260717.json")' in src and "sorted(" in src and "[-1]" in src;c["scope"]=d.get("scope")=="TEST_POINTER_ONLY" and d.get("trainer_or_scientific_behavior")=="UNCHANGED" and d.get("trainer_launched") is False;c["no_launch"]=d.get("launch_authority")=="NONE_UNTIL_V4_LOCK_AUDIT_FULL_TESTS_AND_PREFLIGHT_PASS";c["official_zero"]=d.get("official_hands")==0;c["no_strength"]=d.get("strength_claim")=="FORBIDDEN";failed=[k for k,v in c.items() if not v];o={"schema_version":"v5.hybrid.h14.lock_test_pointer_correction_audit.v1","checked_at":datetime.now(timezone.utc).isoformat(),"correction_sha256":sha(R),"checks":c,"checks_passed":sum(c.values()),"checks_total":len(c),"failed":failed,"overall":"PASS" if not failed else "FAIL_CLOSED","official_hands":0};OUT.write_text(json.dumps(o,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(json.dumps(o,indent=2,sort_keys=True));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
