param([switch]$ValidateOnly)
$ErrorActionPreference='Stop';$Repo=(Resolve-Path '.').Path
$runId='v5_hybrid_h7_control_kl0_same31400_20m_r1_20260713';$runDir=Join-Path $Repo "models/alpha_holdem_v5_hybrid/$runId"
$source=(Resolve-Path 'models/alpha_holdem_v5_from_zero/v5_zero_l6_exp004_pre001_exp002_multienv_exp003_boundedk_r1_20260709/v5_exp005_cutover_gate31400_checkpoint.pt').Path
$prereg=(Resolve-Path 'reports/v5_hybrid_h7_preregistration_20260713.json').Path;$lock=(Resolve-Path 'reports/v5_hybrid_h7_design_lock_20260713.json').Path;$preflight=(Resolve-Path 'reports/v5_hybrid_h7_preflight_20260713.json').Path;$expected='88aea213e00614191b79496079ea8607aca67a0a7d9c582f47a93af011f325af'
if((Get-FileHash $source -Algorithm SHA256).Hash.ToLowerInvariant()-ne'bcbb46bd01d62fcdea602269b7047323315d4e9bbcf447ea0323e289fde11a8e'){throw'source hash'}
if((Get-FileHash $prereg -Algorithm SHA256).Hash.ToLowerInvariant()-ne'45b57f4fe817f1b98e7267a8e482d46b8121fb41d4e432a8af25a1857c6cb4b7'){throw'prereg hash'}
if((Get-FileHash $lock -Algorithm SHA256).Hash.ToLowerInvariant()-ne$expected){throw'lock hash'}
$pf=Get-Content $preflight -Raw|ConvertFrom-Json;if($pf.overall-ne'PASS_READY_H7_CONTROL_LAUNCH'-or$pf.design_lock_sha256-ne$expected){throw'preflight'}
$active=Get-CimInstance Win32_Process|Where-Object{$_.CommandLine-like'*train_v5.py*'-and$_.CommandLine-like'*v5_hybrid_h7_*'};$forbidden=Get-CimInstance Win32_Process|Where-Object{$_.CommandLine-like'*v5_hybrid_h7_mirror.py*'-or$_.CommandLine-like'*slumbot*'}
$ready=(-not$active)-and(-not$forbidden)-and(-not(Test-Path $runDir));if($ValidateOnly){[pscustomobject]@{ready=$ready;run_dir_absent=(-not(Test-Path $runDir));active=@($active).Count;forbidden=@($forbidden).Count}|ConvertTo-Json;exit $(if($ready){0}else{3})};if(-not$ready){throw'H7 control not ready'}
New-Item -ItemType Directory -Path $runDir|Out-Null;$prov=Join-Path $runDir 'opponent_assignment_provenance.jsonl';$out=Join-Path $runDir 'latest.pt'
$args=@('-u','scripts/alpha_holdem/train_v5.py','--resume',$source,'--allow-resume','--reset-optimizer','--run-id',$runId,'--run-dir',$runDir,'--out',$out,'--total-hands','535989661','--device','cuda','--workers','22','--hands-per-iter','16384','--rollout-mode','multi','--rollout-envs-per-worker','16','--inference-min-batch-slots','256','--inference-batch-deadline-us','1000','--ppo-epochs','4','--ppo-target-kl','0','--mini-batch-size','1024','--lr','0.0003','--gamma','0.999','--entropy-coef','0.05','--entropy-floor','0.3','--seed','20260703','--worker-seed-base','73000','--fixed-training-deal-stream','--opponent-assignment','per-iteration','--opponent-assignment-provenance-file',$prov,'--pool-strategy','loss-kbest','--k-best','5','--opponent-groups','5','--self-play-fraction','0.2','--mirror-self-play-deals','--allin-runout-ev','--allin-runout-ev-max-runouts','200','--preflop-action-prior-coef','0.01','--preflop-action-prior-target','0.24,0.36,0.38,0.02','--postflop-action-prior-coef','0.02','--postflop-action-prior-target','0.15,0.30,0.52,0.03','--critic-contract','critic_v1','--value-coef','0.5','--save-interval','1','--snapshot-every','200','--h7-window-arm','control','--h7-preregistration',$prereg,'--h7-preregistration-sha256','45b57f4fe817f1b98e7267a8e482d46b8121fb41d4e432a8af25a1857c6cb4b7','--h7-design-lock',$lock,'--h7-design-lock-sha256',$expected)
$trainer=Start-Process python -ArgumentList $args -WorkingDirectory $Repo -RedirectStandardOutput (Join-Path $runDir 'console.out.log') -RedirectStandardError (Join-Path $runDir 'console.err.log') -WindowStyle Hidden -PassThru;$deadline=(Get-Date).AddSeconds(120);while(-not(Test-Path(Join-Path $runDir 'run_manifest.json'))){if((Get-Date)-gt$deadline){Stop-Process -Id $trainer.Id -Force;throw'manifest timeout'};if($trainer.HasExited){throw"trainer exited $($trainer.ExitCode)"};Start-Sleep 1}
try{powershell -NoProfile -ExecutionPolicy Bypass -File scripts/alpha_holdem/v5_rearm_watchers.ps1 -RunDir $runDir;if($LASTEXITCODE-ne0){throw'rearm failed'}}catch{Stop-Process -Id $trainer.Id -Force -ErrorAction SilentlyContinue;throw};[pscustomobject]@{status='H7_CONTROL_LAUNCHED_REARM_PASS';trainer_pid=$trainer.Id;run_id=$runId}|ConvertTo-Json
