#!/usr/bin/env python3
"""Independent fail-closed audit for immutable H14 preregistration."""
from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]
P=ROOT/"reports/v5_hybrid_h14_preregistration_20260717.json"
OUT=ROOT/"reports/v5_hybrid_h14_preregistration_audit_20260717.json"
def sha(p:Path)->str: return hashlib.sha256(p.read_bytes()).hexdigest()
def main()->int:
 d=json.loads(P.read_text(encoding="utf-8"));c={}
 c["schema"]=d.get("schema_version")=="v5.hybrid.h14.preregistration.v1";c["identity"]=d.get("experiment_id")=="H14";c["registered_no_launch"]=d.get("status")=="REGISTERED_NO_LAUNCH"
 rr=d["route_review"];c["rr_result_hash"]=sha(ROOT/rr["result_path"])==rr["result_sha256"];c["rr_audit_hash"]=sha(ROOT/rr["audit_path"])==rr["audit_sha256"]
 r=json.loads((ROOT/rr["result_path"]).read_text(encoding="utf-8"));c["rr_selected"]=r.get("decision",{}).get("selected_next")==rr["selected_next"] and r.get("decision",{}).get("route_exhausted") is False
 rp=d["control_plane_repair"];c["repair_pending"]=rp.get("status")=="REQUIRED_BEFORE_IMPLEMENTATION_AUDIT_OR_LAUNCH";c["incident_hash"]=sha(ROOT/rp["trigger_incident_path"])==rp["trigger_incident_sha256"];c["terminal_audit_hash"]=sha(ROOT/rp["terminal_audit_path"])==rp["terminal_audit_sha256"]
 c["five_roles"]=rp.get("required_exact_child_roles")==["health","protocol","endpoint","treatment_launch","completion"]
 c["exact_bindings"]=rp.get("binding")==["script_identity","parent_relationship","design_lock_identity","command_line_sha256","full_trigger_provenance"] and rp.get("broad_process_class_allowlist")=="FORBIDDEN"
 c["adversarial_contract"]=rp.get("adversarial_contract")=="REGISTERED_CHILDREN_PASS;UNREGISTERED_SIBLING_OR_COMMAND_MISMATCH_FAILS_CLOSED"
 s=d["source"];source=Path(s["checkpoint_path"]);c["source_hash"]=sha(source)==s["checkpoint_sha256"];c["source_identity"]=s.get("iteration")==35051 and s.get("hands")==576021901 and s.get("optimizer_preserved") is True
 te=d["source_terminal_evidence"]
 for key in ["run_manifest","endpoint_status","protocol_status"]:c[f"{key}_hash"]=sha(ROOT/te[f"{key}_path"])==te[f"{key}_sha256"]
 manifest=json.loads((ROOT/te["run_manifest_path"]).read_text(encoding="utf-8"));endpoint=json.loads((ROOT/te["endpoint_status_path"]).read_text(encoding="utf-8"));protocol=json.loads((ROOT/te["protocol_status_path"]).read_text(encoding="utf-8"))
 c["source_terminal"]=manifest.get("status")=="finished" and endpoint.get("overall")=="PASS" and endpoint.get("state")=="ARM_ENDPOINT_FROZEN" and protocol.get("overall")=="PASS" and protocol.get("state")=="ARM_FINISHED_GUARDS_PASS"
 sv=d["single_variable"];c["single_variable"]=sv.get("control")=="MSE" and sv.get("treatment")=="SmoothL1" and sv.get("treatment_beta_raw_bb")==1.0 and sv.get("standard_ppo_critic_loss_both_arms")=="MSE";c["no_outcome_search"]="no CAL-EXT-002" in sv.get("beta_selection","")
 fs=d["forbidden_sources"];c["forbidden_sources"]=len(fs)==7 and any("H13 attempted" in x for x in fs) and any("benchmark" in x for x in fs)
 a=d["arms"];c["fresh_fixed_arms"]=a.get("order")==["control","treatment"] and a.get("actual_hands_each")==20000000 and a.get("minimum_endpoint_hands")==596021901 and a.get("maximum_overshoot_hands")==50000 and a.get("fresh_same_start") is True;c["no_adaptation"]=all(a.get(k) is False for k in ["adaptive_extension","second_seed","later_endpoint","terminal_partial_reuse"]);c["h14_run_ids"]="v5_hybrid_h14_control_" in a.get("control_run_id","") and "v5_hybrid_h14_treatment_" in a.get("treatment_run_id","")
 cfg=d["frozen_common_config"];expected={"target_kl":0.03,"value_head_catchup_after_kl_stop":True,"critic_contract":"critic_v1","value_coef":0.5,"ppo_epochs":4,"mini_batch_size":1024,"workers":22,"rollout_mode":"multi","rollout_envs_per_worker":16,"fixed_training_deal_stream":True,"opponent_assignment":"per-iteration","preflop_action_prior_coef":0.01,"postflop_action_prior_coef":0.02,"optimizer_reset":False};c["common_config"]=all(cfg.get(k)==v for k,v in expected.items());c["allin_ev"]=cfg.get("mirror_self_play_deals") is True and cfg.get("allin_runout_ev") is True and cfg.get("allin_runout_ev_max_runouts")==200
 pc=d["performance_calibration"];c["perf_cal_exact"]=pc.get("required_immediately_before_each_arm") is True and pc.get("control_seed")==2026071703 and pc.get("treatment_seed")==2026071704 and pc.get("batch_size")==1024 and pc.get("warmup_steps")==10 and pc.get("timed_steps")==40 and pc.get("repeats")==3 and pc.get("loss_throughput_ratio_min")==0.95 and pc.get("treatment_common_mse_control_baseline_ratio_min")==0.95;c["perf_cal_no_launch"]=pc.get("failure_action")=="FAIL_CLOSED_NO_ARM_LAUNCH" and "H14_DESIGN_LOCK" in pc.get("tool_hashes","")
 cp=d["control_plane"];c["startup_pending"]=cp.get("startup_log_missing")=="PENDING_UNTIL_180_SECONDS_THEN_FAIL_CLOSED";c["child_roles"]=cp.get("allowed_child_roles")==["health","protocol","endpoint","treatment_launch","completion"];c["child_binding"]="EXACT_SCRIPT_PARENT_RELATIONSHIP_DESIGN_LOCK_AND_COMMAND_LINE_SHA256"==cp.get("allowed_child_binding") and cp.get("broad_process_class_allowlist")=="FORBIDDEN";c["unregistered_fail"]=cp.get("unregistered_sibling_or_command_mismatch","").startswith("FAIL_CLOSED_FULL_PROVENANCE");c["rearm_launcher"]=cp.get("canonical_rearm_survival_failure")=="STATUS_FALSE_AND_EXIT_NONZERO" and cp.get("launcher_rearm_success")=="PROCESS_EXIT_ZERO_AND_STATUS_SURVIVAL_PASS_TRUE";c["stage_order"]=cp.get("control_stage_order")==[["health","protocol"],["endpoint"],["treatment_launch","completion"]] and cp.get("treatment_stage_order")==[["health","protocol"],["endpoint"],["completion"]]
 ri=d["resource_isolation"];c["isolation"]=ri.get("evaluation_during_arm")==ri.get("slumbot_during_arm")=="FORBIDDEN" and "INCLUDING_FILE_READ_HASH_PROCESS_LIST" in ri.get("parent_or_delegated_observer_commands","");c["path1_policy"]="PID23720_SIX_BELOWNORMAL_CPU_WORKERS_NO_RESTART_EXPANSION_OR_NEW_WORKERS" in ri.get("path1_existing_job","");c["provenance"]=ri.get("full_trigger_provenance")==["pid","parent_pid","creation_time","executable","command_line","command_line_sha256"]
 g=d["gates"];expected_g={"endpoint_mse_primary_reduction_point_min":0.075,"endpoint_mse_primary_ci95_lower_min":0.0,"source_anchor_degradation_point_max":0.05,"source_anchor_degradation_ci95_upper_max":0.1,"kl_p95_max":0.03,"first60_hps_ratio_min":0.85,"full_hps_ratio_min":0.85,"entropy_median_last200_min":0.3,"entropy_treatment_minus_control_min":-0.1,"mirror_pairs":40000,"mirror_treatment_control_ci95_lower_min_bb100":-20.0,"mirror_treatment_source_ci95_lower_min_bb100":-20.0};c["science_gates"]=all(g.get(k)==v for k,v in expected_g.items())
 j=d["judgment"];c["terminal_verdicts"]=all(k in j for k in ["pass","fail","inconclusive"]) and j.get("route_review_after_fail_or_inconclusive") is True
 ep=d["external_policy"];c["external_debt"]=ep.get("latest_complete_official_checkpoint_hands")==576021901 and ep.get("current_external_debt_hands")==0 and ep.get("expected_endpoint_external_debt_hands")==20000000;c["method_pass_quick5k"]="H14_TREATMENT_GREEDY_DIRECT_QUICK5K" in ep.get("method_pass_next","");c["no_official_during_arms"]=ep.get("during_arms_official_hands")==0
 au=d["authority"];c["launch_blocked"]=au.get("launch","").startswith("BLOCKED_UNTIL_H14_");c["official_zero"]=au.get("official_hands")==0;c["no_strength"]=au.get("strength_claim")=="FORBIDDEN";c["holdout_forbidden"]="FORBIDDEN_HOLDOUT_ONLY" in d.get("holdout","")
 failed=sorted(k for k,v in c.items() if not v);out={"schema_version":"v5.hybrid.h14.preregistration_audit.v1","checked_at":datetime.now(timezone.utc).isoformat(),"preregistration_sha256":sha(P),"checks":c,"checks_passed":sum(c.values()),"checks_total":len(c),"failed":failed,"overall":"PASS" if not failed else "FAIL_CLOSED","launch_authority":"NONE_REGISTRATION_AUDIT_ONLY","official_hands":0,"strength_claim":"FORBIDDEN"};OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(json.dumps(out,indent=2,sort_keys=True));return 0 if not failed else 1
if __name__=="__main__":raise SystemExit(main())
